CREATE TABLE users (
	id	BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	username	VARCHAR(100)	UNIQUE NOT NULL,
	password_hash	VARCHAR(255)	NOT NULL,
	created_at	TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE pages (
	id	BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ftp_path	VARCHAR(200)	NOT NULL,
	title	VARCHAR(200)	NOT NULL,
	updated_at	TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE blocks (
	id	BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	page_id   BIGINT NOT NULL,
	CONSTRAINT fk_blocks_page
		FOREIGN KEY (page_id)
		REFERENCES pages(id)
		ON DELETE CASCADE,
	selector	VARCHAR(100)	NOT NULL,
	type VARCHAR(10) NOT NULL CHECK (type IN ('text', 'image')),
    constraints JSONB NOT NULL
);
CREATE TABLE revisions (
	id	BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	page_id   BIGINT NOT NULL,
	CONSTRAINT fk_revisions_page
		FOREIGN KEY (page_id)
		REFERENCES pages(id)
		ON DELETE CASCADE,
	payload JSONB NOT NULL,
	created_at	TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_revisions_payload ON revisions USING gin (payload);